name: password_app
description: "A new Flutter project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0-nullsafety.0
  fluttericon: ^2.0.0
  flutter_keyboard_visibility: ^5.0.1
  connectivity: ^3.0.3
  crypto: ^3.0.1
  encrypt: ^5.0.0
  clipboard: ^0.1.3
  flash: ^1.5.1
  csv: ^5.0.0
  file_picker: ^3.0.1
  dio: ^4.0.0
  provider: ^5.0.0
  device_info: ^2.0.0
  url_launcher: ^6.0.3
  firebase_messaging: ^9.1.1
  firebase_core: ^1.0.3
  flutter_local_notifications: ^5.0.0+1
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0